install.packages("BiocManager")
BiocManager::install("minfi", lib="~/R/x86_64-pc-linux-gnu-library/4.1")
BiocManager::install("ENmix", lib="~/R/x86_64-pc-linux-gnu-library/4.1")
BiocManager::install("wateRmelon", lib="~/R/x86_64-pc-linux-gnu-library/4.1")
install.packages("MASS")
install.packages("broom")
install.packages("RColorBrewer")
install.packages("optparse")
BiocManager::install("IlluminaHumanMethylationEPICmanifest", lib="~/R/x86_64-pc-linux-gnu-library/4.1")
BiocManager::install("IlluminaHumanMethylationEPICanno.ilm10b4.hg19", lib="~/R/x86_64-pc-linux-gnu-library/4.1")
BiocManager::install("IlluminaHumanMethylation450kmanifest", lib="~/R/x86_64-pc-linux-gnu-library/4.1")
BiocManager::install("IlluminaHumanMethylation450kanno.ilmn12.hg19", lib="~/R/x86_64-pc-linux-gnu-library/4.1")
